[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai-rust = { path = "../../openai-rust" }
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"